# This is a basic workflow to help you get started with Actions

name: run-vercel

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: "00 12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  AIRTABLE_API_KEY: ${{secrets.AIRTABLE_API_KEY}}
  GENSHIN_AIRTABLE_BASE_KEY: ${{secrets.GENSHIN_AIRTABLE_BASE_KEY}}
  GENSHIN_AIRTABLE_TABLE_KEY: ${{secrets.GENSHIN_AIRTABLE_TABLE_KEY}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo starting workflow!

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7        
      - name: install python packages
        run: pip install -r requirements.txt
      - name: Install dependencies
        run: |      
          python -m playwright install  
      - name: run script
        run: python  scrape.py -k "vercel" -n vercel

      - name: commit
        run: |
          git config --global user.email action@github.com
          git config --global user.name action
          git add .
          git commit -m "update db" -a
          git pull
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
